In [25]:
import csv
import os
import pandas as pd
from pprint import pprint

#read in .csv file
hospital_data = pd.read_csv("../hospitals.csv")

#set index to state_name
hospital_data.set_index("state_name",inplace=True)

#group dataframe by state_name
hg = hospital_data.groupby('state_name')

#do count of hg dataframe (where it groups by states)to get total count of hospitals, doctors, staff,
#icu beds, and icu beds utilized. Then add each series to new dataframe called 'state_hospital_data'

hg["num_icu_be"].count()
state_hospital_data = pd.DataFrame(hg["num_icu_be"].count())

hospitals = hg["hospital_n"].count()
state_hospital_data["Number of Hospitals"]=hospitals

doctors = hg["num_licens"].count()
state_hospital_data["Number of Doctors"]=doctors

staff = hg["num_staffe"].count()
state_hospital_data["Number of Staff"]=staff

icu_beds = hg["num_icu_be"].count()
state_hospital_data["ICU Beds Available"]=icu_beds

bed_utiliz = hg["bed_utiliz"].count()
state_hospital_data["ICU Beds Utilized"]=bed_utiliz

#drop double num_icu_be column
state_hospital_data.drop("num_icu_be",axis=1)

#final data frame
state_hospital_data

,num_icu_be,Number of Hospitals,Number of Doctors,Number of Staff,ICU Beds Available,ICU Beds Utilized
state_name,,,,,,
Alabama,66,120,120,120,66,109
Alaska,7,28,28,28,7,23
Arizona,46,126,126,126,46,108
Arkansas,40,106,106,106,40,100
California,302,466,466,466,302,401
Colorado,48,113,113,113,48,101
Connecticut,25,46,46,46,25,40
Delaware,5,16,16,16,5,15
District of Columbia,6,14,14,14,6,12
Florida,172,276,276,276,172,250
Georgia,87,180,180,180,87,164
Hawaii,14,29,29,29,14,23
Idaho,15,53,53,53,15,47
Illinois,118,215,215,215,118,199
Indiana,81,177,177,177,81,161
Iowa,35,124,124,124,35,121
Kansas,41,164,164,164,41,147
Kentucky,65,119,119,119,65,112
Louisiana,66,221,221,221,66,202
Maine,19,39,39,39,19,38
Maryland,43,66,66,66,43,58
Massachusetts,51,110,110,110,51,96
Michigan,88,171,171,171,88,161
Minnesota,47,148,148,148,47,139
Mississippi,38,114,114,114,38,106
Missouri,66,151,151,151,66,134
Montana,16,67,67,67,16,65
Nebraska,19,101,101,101,19,98
Nevada,23,67,67,67,23,55
New Hampshire,17,34,34,34,17,30
New Jersey,62,101,101,101,62,95
New Mexico,26,57,57,57,26,54
New York,127,230,230,230,127,197
North Carolina,82,145,145,145,82,128
North Dakota,8,54,54,54,8,49
Ohio,122,251,251,251,122,225
Oklahoma,45,157,157,157,45,142
Oregon,38,69,69,69,38,62
Pennsylvania,125,246,246,246,125,219
Puerto Rico,36,50,50,50,36,44
Rhode Island,8,15,15,15,8,13
South Carolina,52,93,93,93,52,79
South Dakota,13,66,66,66,13,60
Tennessee,68,149,149,149,68,138
Texas,222,644,644,644,222,554
Utah,27,62,62,62,27,56
Vermont,7,17,17,17,7,16
Virginia,68,124,124,124,68,109
Washington,50,116,116,116,50,101
West Virginia,28,67,67,67,28,58
Wisconsin,72,150,150,150,72,144
Wyoming,11,33,33,33,11,29