In [2]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time

from pprint import pprint

In [16]:
# import csv file that is a breakdown of cases and deaths per day by state and county
df = pd.read_csv("us-counties.csv.txt")

#group by state and date so that data is no longer at the county level, but at the state level
state_df = df.groupby(["state","date"])

#Create a data frame that has total cases by date by state
cases = state_df["cases"].sum()
workable_df = pd.DataFrame(cases)
workable_df = workable_df.reset_index()

#get the data for deaths per state per day into a series format to add to the cases dataframe
deaths = state_df["deaths"].sum()
death=pd.DataFrame(deaths)
work_death=death.reset_index()
DEAD = work_death["deaths"]

# Add Deaths column to the cases dataframe
workable_df["Deaths"]=DEAD

#Create final dataframe with just the columns we are interested in
final_df = workable_df[["date","state","cases","Deaths"]]

#Sort final df by date and re-index
final_df = final_df.sort_values("date")
final_df = final_df.reset_index(drop = True)
final_df

            date       state   cases  Deaths
0     2020-01-21  Washington       1       0
1     2020-01-22  Washington       1       0
2     2020-01-23  Washington       1       0
3     2020-01-24    Illinois       1       0
4     2020-01-24  Washington       1       0
...          ...         ...     ...     ...
2209  2020-04-11  New Mexico    1174      20
2210  2020-04-11    New York  180458    8627
2211  2020-04-11     Georgia   12261     432
2212  2020-04-11    Nebraska     729      18
2213  2020-04-11     Wyoming     261       0

[2214 rows x 4 columns]

In [5]:
#Liz's Hospital Dataframe

import csv
import os
import pandas as pd
from pprint import pprint

#read in .csv file
hospital_data = pd.read_csv("../hospitals.csv")

#set index to state_name
hospital_data.set_index("state_name",inplace=True)

#group dataframe by state_name
hg = hospital_data.groupby('state_name')

#do count of hg dataframe (where it groups by states)to get total count of hospitals, doctors, staff,
#icu beds, and icu beds utilized. Then add each series to new dataframe called 'state_hospital_data'

hg["num_icu_be"].count()
state_hospital_data = pd.DataFrame(hg["num_icu_be"].count())

hospitals = hg["hospital_n"].count()
state_hospital_data["Number of Hospitals"]=hospitals

doctors = hg["num_licens"].count()
state_hospital_data["Number of Doctors"]=doctors

staff = hg["num_staffe"].count()
state_hospital_data["Number of Staff"]=staff

icu_beds = hg["num_icu_be"].count()
state_hospital_data["ICU Beds Available"]=icu_beds

bed_utiliz = hg["bed_utiliz"].count()
state_hospital_data["ICU Beds Utilized"]=bed_utiliz

#drop double num_icu_be column
state_hospital_data.drop("num_icu_be",axis=1)

#final data frame
state_hospital_data